// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddLanguageForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"></head><body><div class=\"container mt-4\"><h1>Add a Programming Language</h1><form method=\"POST\" action=\"/languages/add\" class=\"needs-validation\" novalidate><div class=\"mb-3\"><label for=\"name\" class=\"form-label\">Name</label> <input type=\"text\" class=\"form-control\" id=\"name\" name=\"Name\" required><div class=\"invalid-feedback\">Please provide a name for the programming language.</div></div><div class=\"mb-3\"><label for=\"paradigm\" class=\"form-label\">Paradigm</label> <input type=\"text\" class=\"form-control\" id=\"paradigm\" name=\"Paradigm\" required><div class=\"invalid-feedback\">Please specify the paradigm of the programming language.</div></div><div class=\"mb-3\"><label for=\"firstAppeared\" class=\"form-label\">First Appeared</label> <input type=\"number\" class=\"form-control\" id=\"firstAppeared\" name=\"FirstAppeared\" min=\"1950\" max=\"2024\" required><div class=\"invalid-feedback\">Please specify a valid year between 1950 and 2024.</div></div><button type=\"submit\" class=\"btn btn-primary\">Add Language</button></form><a href=\"/\" class=\"btn btn-secondary mt-3\">Back to List</a></div><script>\n\t\t\t\t(function () {\n\t\t\t\t\t'use strict';\n\t\t\t\t\tconst forms = document.querySelectorAll('.needs-validation');\n\t\t\t\t\tArray.prototype.slice.call(forms).forEach(function (form) {\n\t\t\t\t\t\tform.addEventListener('submit', function (event) {\n\t\t\t\t\t\t\tif (!form.checkValidity()) {\n\t\t\t\t\t\t\t\tevent.preventDefault();\n\t\t\t\t\t\t\t\tevent.stopPropagation();\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\tform.classList.add('was-validated');\n\t\t\t\t\t\t}, false);\n\t\t\t\t\t});\n\t\t\t\t})();\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
